// +build ignore

// TEMPORARY AUTOGENERATED FILE: easyjson bootstapping code to launch
// the actual generator.

package main

import (
  "fmt"
  "os"

  "github.com/mailru/easyjson/gen"

  pkg "json-server-kit/apps/common/model/dto"
)

func main() {
  g := gen.NewGenerator("dto_easyjson.go")
  g.SetPkg("dto", "json-server-kit/apps/common/model/dto")
  g.Add(pkg.EasyJSON_exporter_CreateDictTypeDTO(nil))
  g.Add(pkg.EasyJSON_exporter_DictTypeQuery(nil))
  if err := g.Run(os.Stdout); err != nil {
    fmt.Fprintln(os.Stderr, err)
    os.Exit(1)
  }
}
