// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package vo

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson32904fcDecodeJsonServerKitAppsAuthModelVo(in *jlexer.Lexer, out *CaptchaVO) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.ID = string(in.String())
		case "captcha":
			out.Captcha = string(in.String())
		case "enabled":
			out.Enabled = bool(in.Bool())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson32904fcEncodeJsonServerKitAppsAuthModelVo(out *jwriter.Writer, in CaptchaVO) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.String(string(in.ID))
	}
	{
		const prefix string = ",\"captcha\":"
		out.RawString(prefix)
		out.String(string(in.Captcha))
	}
	{
		const prefix string = ",\"enabled\":"
		out.RawString(prefix)
		out.Bool(bool(in.Enabled))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CaptchaVO) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson32904fcEncodeJsonServerKitAppsAuthModelVo(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CaptchaVO) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson32904fcEncodeJsonServerKitAppsAuthModelVo(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CaptchaVO) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson32904fcDecodeJsonServerKitAppsAuthModelVo(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CaptchaVO) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson32904fcDecodeJsonServerKitAppsAuthModelVo(l, v)
}
