logger:
  director: ./logs
  log-in-terminal: true
  show-line-number: true
system:
  routes-print-able: true
i18n:
  default-lng: zh-CN
  lngs:
    - zh-CN
  path: ./locales
cors:
  allow-methods:
    - GET
    - POST
    - PUT
    - DELETE
  allow-headers:
    - Content-Type
    - Authorization
  allow-credentials: true
  max-age: 12h
  allow-origins:
    - "*"
