definitions:
  dto.CreateDictTypeDTO:
    properties:
      code:
        type: string
      desc:
        type: string
      name:
        type: string
      status:
        type: boolean
    required:
    - code
    - name
    type: object
  dto.UsernameLoginWithCaptchaDTO:
    properties:
      captcha:
        description: 验证码
        type: string
      captchaId:
        description: 验证码ID
        type: string
      password:
        description: 密码
        type: string
      username:
        description: 用户名
        type: string
    type: object
  entity.DictItem:
    properties:
      classList:
        description: 样式列表
        type: string
      color:
        description: 颜色
        type: string
      createdAt:
        description: 创建时间
        type: string
      createdBy:
        description: 创建人
        type: string
      desc:
        description: 字典项描述
        type: string
      dictTypeId:
        description: 字典类型ID
        type: integer
      id:
        description: 主键ID
        type: integer
      isDefault:
        description: 是否默认
        type: boolean
      key:
        description: 字典项键
        type: string
      name:
        description: 字典项名称
        type: string
      sort:
        description: 排序
        type: integer
      status:
        description: '状态(1: 正常, 0: 禁用)'
        type: boolean
      updatedAt:
        description: 更新时间
        type: string
      updatedBy:
        description: 更新人
        type: string
      value:
        description: 字典项值
        type: string
    type: object
  entity.DictType:
    properties:
      code:
        description: 字典编码
        type: string
      createdAt:
        description: 创建时间
        type: string
      createdBy:
        description: 创建人
        type: string
      desc:
        description: 描述
        type: string
      id:
        description: 主键ID
        type: integer
      items:
        items:
          $ref: '#/definitions/entity.DictItem'
        type: array
      name:
        description: 字典名称
        type: string
      status:
        description: 状态
        type: boolean
      updatedAt:
        description: 更新时间
        type: string
      updatedBy:
        description: 更新人
        type: string
    type: object
  entity.User:
    properties:
      createdAt:
        description: 创建时间
        type: string
      createdBy:
        description: 创建人
        type: string
      email:
        description: 邮箱
        type: string
      enable:
        description: 是否启用
        type: boolean
      id:
        description: 主键ID
        type: string
      nickname:
        description: 昵称
        type: string
      phone:
        description: 手机号
        type: string
      updatedAt:
        description: 更新时间
        type: string
      updatedBy:
        description: 更新人
        type: string
      username:
        description: 用户名
        type: string
    type: object
  utils.BaseResponseVO:
    properties:
      code:
        type: integer
      data: {}
      msg:
        type: string
      time:
        type: string
    type: object
  vo.CaptchaVO:
    properties:
      captcha:
        description: 验证码
        type: string
      enabled:
        description: 是否启用
        type: boolean
      id:
        description: 验证码ID
        type: string
    type: object
info:
  contact: {}
paths:
  /auth/captcha:
    get:
      consumes:
      - application/json
      description: 获取验证码
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/utils.BaseResponseVO'
            - properties:
                data:
                  $ref: '#/definitions/vo.CaptchaVO'
              type: object
      summary: 获取验证码
      tags:
      - auth
  /auth/login:
    post:
      consumes:
      - application/json
      description: 用户名密码登录(需要验证码)
      parameters:
      - description: 登录信息
        in: body
        name: loginDTO
        required: true
        schema:
          $ref: '#/definitions/dto.UsernameLoginWithCaptchaDTO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/utils.BaseResponseVO'
            - properties:
                data:
                  $ref: '#/definitions/entity.User'
              type: object
      summary: 用户名密码登录
      tags:
      - auth
  /common/dict/${code}/values:
    get:
      consumes:
      - application/json
      description: 获取字典值列表
      parameters:
      - description: 字典类型编码
        enum:
        - sys_user_sex
        - sys_user_status
        in: path
        name: code
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/utils.BaseResponseVO'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/entity.DictItem'
                  type: array
              type: object
      summary: 获取字典值列表
      tags:
      - common
  /common/dict/types:
    get:
      consumes:
      - application/json
      description: 获取字典类型
      parameters:
      - in: query
        name: code
        type: string
      - in: query
        name: id
        type: integer
      - in: query
        name: name
        type: string
      - in: query
        name: status
        type: boolean
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/utils.BaseResponseVO'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/entity.DictType'
                  type: array
              type: object
      summary: 获取字典类型
      tags:
      - common
    post:
      consumes:
      - application/json
      description: 新增字典类型
      parameters:
      - description: 新增字典类型信息
        in: body
        name: createDictTypeDTO
        required: true
        schema:
          $ref: '#/definitions/dto.CreateDictTypeDTO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/utils.BaseResponseVO'
            - properties:
                data:
                  $ref: '#/definitions/entity.DictType'
              type: object
      summary: 新增字典类型
      tags:
      - common
swagger: "2.0"
