info:
  contact: {}
paths:
  /example:
    get:
      consumes:
      - application/json
      description: HelloWorld
      produces:
      - application/json
      responses:
        "200":
          description: Hello World
          schema:
            type: string
      summary: HelloWorld
      tags:
      - example
swagger: "2.0"
